services:
  api:
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile 
      target: api-runner
    ports:
      - '3000:3000'
    networks:
      - prisma-network
      - redis-network
    env_file:
      - .env
    depends_on:
      - db
      - redis

  ingestion:
    container_name: ingestion
    build:
      context: .
      dockerfile: Dockerfile
      target: ingestion-runner
    ports:
      - '5000:3000'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - prisma-network
      - redis-network

  db:
    container_name: postgres
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nest_ingestion"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    container_name: redis
    image: 'redis:alpine'
    env_file:
      - .env
    ports:
      - '6379:6379'
    networks:
      - redis-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

networks:
  redis-network:
    name: redis-network
  prisma-network:
    name: prisma-network

volumes:
  postgres_data: