services:
  api:
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  ingestion:
    container_name: ingestion
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:3000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'